---
- hosts: all
- name:  dynamic variables 
import_playbook: ../static-assignments/common.yml 
include: ../dynamic-assignments/env-vars.yml
tags:
  - always
- hosts: webservers
- name: Webserver assignment
import_playbook: ../static-assignments/uat-webservers.yml
